"""esquema inicial

NOTA: o autogenerate do Alembic renderiza `astext_type=sa.Text()` sem o prefixo
`sa.`, o que quebra com NameError ao aplicar. A correção é manual e precisa ser
refeita a cada migração que toque colunas JSONB.

Revision ID: f1d99c583f30
Revises: 
Create Date: 2026-07-28 13:56:48.960308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d99c583f30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('minimum_number', sa.SmallInteger(), nullable=False),
    sa.Column('maximum_number', sa.SmallInteger(), nullable=False),
    sa.Column('numbers_drawn', sa.SmallInteger(), nullable=False),
    sa.Column('minimum_bet_size', sa.SmallInteger(), nullable=False),
    sa.Column('maximum_bet_size', sa.SmallInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('maximum_bet_size >= minimum_bet_size', name='aposta_coerente'),
    sa.CheckConstraint('maximum_number > minimum_number', name='universo_coerente'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('age_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_budget_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint('email = lower(email)', name='users_email_minusculo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('contest_number', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('drawn_numbers', postgresql.ARRAY(sa.SmallInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('accumulated', sa.Boolean(), nullable=False),
    sa.Column('estimated_prize', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('contest_number > 0', name='concurso_positivo'),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'contest_number', name='concurso_unico')
    )
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.create_index('draws_por_concurso', ['lottery_id', 'contest_number'], unique=False)

    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('rejection_log', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('bet_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.CheckConstraint('bet_price > 0', name='preco_positivo'),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'valid_from', name='preco_unico_por_vigencia')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='estrategia_unica_por_usuario')
    )
    op.create_table('prize_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('hits', sa.SmallInteger(), nullable=False),
    sa.Column('winners', sa.Integer(), nullable=False),
    sa.Column('prize_per_winner', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.CheckConstraint('hits >= 0 AND winners >= 0 AND prize_per_winner >= 0', name='faixa_nao_negativa'),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_id', 'hits', name='faixa_unica_por_concurso')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name='versao_positiva'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='versao_unica')
    )
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('dev_from', sa.Integer(), nullable=False),
    sa.Column('dev_to', sa.Integer(), nullable=False),
    sa.Column('val_from', sa.Integer(), nullable=True),
    sa.Column('val_to', sa.Integer(), nullable=True),
    sa.Column('test_from', sa.Integer(), nullable=False),
    sa.Column('test_to', sa.Integer(), nullable=False),
    sa.Column('games_per_draw', sa.Integer(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('gross_prizes', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_return', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('random_baseline_roi', sa.Float(), nullable=False),
    sa.Column('percentile_vs_random', sa.Float(), nullable=False),
    sa.Column('simulations', sa.Integer(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('p_value_adjusted', sa.Float(), nullable=True),
    sa.Column('correction_method', sa.Text(), nullable=True),
    sa.Column('hypotheses_tested', sa.Integer(), nullable=False),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('ci_lower', sa.Float(), nullable=True),
    sa.Column('ci_upper', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('overfitting_index', sa.Float(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('dev_from <= dev_to AND (val_from IS NULL OR (dev_to < val_from AND val_from <= val_to)) AND test_from <= test_to AND test_from > COALESCE(val_to, dev_to)', name='particao_cronologica'),
    sa.CheckConstraint('percentile_vs_random BETWEEN 0 AND 100', name='percentil_valido'),
    sa.CheckConstraint('simulations > 0', name='simulacoes_positivas'),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.Integer(), nullable=True),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('numbers', postgresql.ARRAY(sa.SmallInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('validation_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('train_to', sa.Integer(), nullable=False),
    sa.Column('test_from', sa.Integer(), nullable=False),
    sa.Column('test_to', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('gross_prizes', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.CheckConstraint('train_to < test_from AND test_from <= test_to', name='janela_nao_invade_treino'),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_windows')
    op.drop_table('generated_games')
    op.drop_table('backtests')
    op.drop_table('strategy_versions')
    op.drop_table('prize_tiers')
    op.drop_table('strategies')
    op.drop_table('price_history')
    op.drop_table('import_runs')
    with op.batch_alter_table('draws', schema=None) as batch_op:
        batch_op.drop_index('draws_por_concurso')

    op.drop_table('draws')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('lotteries')
    # ### end Alembic commands ###
