/* LotoLab 4.18: núcleo descritivo puro, compartilhado pelo worker e pelos testes. */
(function(root){
'use strict';
const VERSION='4.18.0';
const aviso='Este índice mede semelhança com o histórico. Não representa a probabilidade matemática de a combinação ser sorteada no próximo concurso.';
const rules={
 'mega-sena':{nome:'Mega-Sena',N:60,k:6,min:6,max:20,base:1,preco:6,faixas:[6,5,4],slug:'megasena'},
 'mega-da-virada':{nome:'Mega da Virada',N:60,k:6,min:6,max:20,base:1,preco:6,faixas:[6,5,4],slug:'megasena',especial:true},
 lotofacil:{nome:'Lotofácil',N:25,k:15,min:15,max:20,base:1,preco:3.5,faixas:[15,14,13,12,11],slug:'lotofacil'},
 quina:{nome:'Quina',N:80,k:5,min:5,max:15,base:1,preco:3,faixas:[5,4,3,2],slug:'quina'},
 lotomania:{nome:'Lotomania',N:100,k:20,min:50,max:50,base:0,preco:3,faixas:[20,19,18,17,16,15,0],slug:'lotomania'},
 'dupla-sena':{nome:'Dupla Sena',N:50,k:6,min:6,max:15,base:1,preco:3,faixas:[6,5,4,3],slug:'duplasena',dupla:true},
 timemania:{nome:'Timemania',N:80,k:7,min:10,max:10,base:1,preco:3.5,faixas:[7,6,5,4,3],slug:'timemania',extra:'time',extraN:80},
 'dia-de-sorte':{nome:'Dia de Sorte',N:31,k:7,min:7,max:15,base:1,preco:2.5,faixas:[7,6,5,4],slug:'diadesorte',extra:'mes',extraN:12},
 'mais-milionaria':{nome:'+Milionária',N:50,k:6,min:6,max:12,base:1,preco:6,faixas:[6,5,4,3,2],slug:'maismilionaria',extra:'trevos',extraN:6},
 'super-sete':{nome:'Super Sete',N:10,k:7,min:7,max:21,base:0,preco:3,faixas:[7,6,5,4,3],slug:'supersete',colunas:true}
};
const cfg=m=>{if(!Object.hasOwn(rules,m))throw Error('Modalidade inválida.');return rules[m];};
const sum=a=>a.reduce((x,y)=>x+y,0),mean=a=>a.length?sum(a)/a.length:0;
const sd=a=>{const u=mean(a);return Math.sqrt(sum(a.map(x=>(x-u)**2))/Math.max(1,a.length-1));};
function comb(n,k){if(k<0||k>n)return 0;let v=1;for(let i=1;i<=Math.min(k,n-k);i++)v=v*(n-i+1)/i;return Math.round(v);}
function hash(s){let h=2166136261;for(const c of String(s))h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
function rng(seed){let t=hash(seed);return ()=>{t+=0x6D2B79F5;let x=t;x=Math.imul(x^x>>>15,x|1);x^=x+Math.imul(x^x>>>7,x|61);return ((x^x>>>14)>>>0)/4294967296;};}
function sample(xs,n,r){const a=xs.slice();for(let i=0;i<n;i++){const j=i+Math.floor(r()*(a.length-i));[a[i],a[j]]=[a[j],a[i]];}return a.slice(0,n).sort((a,b)=>a-b);}
function nums(x){const a=Array.isArray(x)?x:String(x??'').trim().split(/[\s,;]+/).filter(Boolean);if(a.some(v=>typeof v==='boolean'||v===null||!/^\d+$/.test(String(v))))throw Error('Use números inteiros separados por espaços.');return a.map(Number);}
function unique(a,lo,hi){if(new Set(a).size!==a.length||a.some(n=>!Number.isInteger(n)||n<lo||n>hi))throw Error('Números repetidos ou fora do intervalo.');return a.slice().sort((a,b)=>a-b);}
function validateTicket(m,t,{resultado=false,completo=false}={}){
 const c=cfg(m),out={};
 if(c.colunas){const cols=t.colunas||(resultado?t.dezenas?.map(x=>[x]):null);if(!Array.isArray(cols)||cols.length!==7)throw Error('Informe sete colunas em ordem, separadas por |.');out.colunas=cols.map(a=>unique(nums(a),0,9));const sizes=out.colunas.map(a=>a.length),n=sum(sizes);if(resultado?sizes.some(x=>x!==1):sizes.some(x=>x<1||x>3)||(n<=14&&sizes.some(x=>x>2))||(n>14&&sizes.some(x=>x<2)))throw Error('Até 14 marcações: 1–2 por coluna. De 15–21: 2–3 por coluna.');}
 else{out.dezenas=unique(nums(t.dezenas),c.base,c.base+c.N-1);const n=out.dezenas.length;if(resultado?n!==c.k:n<c.min||n>c.max)throw Error(resultado?`Resultado exige ${c.k} dezenas.`:`Escolha de ${c.min} a ${c.max} dezenas.`);}
 if(c.extra==='trevos'&&t.trevos!==undefined&&t.trevos!==''){out.trevos=unique(nums(t.trevos),1,6);if(out.trevos.length<2||out.trevos.length>(resultado?2:6))throw Error('Trevos inválidos: dois no resultado e de dois a seis na aposta.');}
 if(['mes','time'].includes(c.extra)&&t[c.extra]!==undefined&&t[c.extra]!==''){const x=Number(t[c.extra]);if(!Number.isInteger(x)||x<1||x>c.extraN)throw Error(`Informe ${c.extra} entre 1 e ${c.extraN}.`);out[c.extra]=x;}
 if(completo&&c.extra&&out[c.extra]===undefined)throw Error('Preencha o complemento: '+c.extra+'.');return out;
}
function parseTicket(m,input,extras={}){const c=cfg(m);let t;if(c.colunas){const a=Array.isArray(input)?input:String(input).trim().split('|');t={colunas:a.length===1?nums(a[0]).map(x=>[x]):a.map(nums)};}else t={dezenas:nums(input)};return validateTicket(m,{...t,...extras});}
const tokens=(m,t)=>cfg(m).colunas?t.colunas.flatMap((a,i)=>a.map(x=>i*10+x)):t.dezenas.map(x=>x-cfg(m).base);
const key=(m,t)=>JSON.stringify(validateTicket(m,t));
function mask(xs){const a=new Uint32Array(4);for(const x of xs)a[x>>>5]|=1<<(x&31);return a;}
function pop(x){x=x-((x>>>1)&0x55555555);x=(x&0x33333333)+((x>>>2)&0x33333333);return (((x+(x>>>4))&0x0F0F0F0F)*0x01010101)>>>24;}
const intersection=(a,b)=>pop(a[0]&b[0])+pop(a[1]&b[1])+pop(a[2]&b[2])+pop(a[3]&b[3]);
const hits=(m,t,r)=>intersection(mask(tokens(m,t)),mask(tokens(m,r)));
function randomTicket(m,r,shape){const c=cfg(m);let t=c.colunas?{colunas:Array.from({length:7},(_,i)=>sample(Array.from({length:10},(_,x)=>x),shape?.colunas?.[i]?.length||1,r))}:{dezenas:sample(Array.from({length:c.N},(_,i)=>i+c.base),shape?.dezenas?.length||c.min,r)};if(c.extra==='trevos')t.trevos=sample([1,2,3,4,5,6],shape?.trevos?.length||2,r);if(['mes','time'].includes(c.extra))t[c.extra]=1+Math.floor(r()*c.extraN);return t;}
function isoDate(s){s=String(s??'');if(/^\d{2}\/\d{2}\/\d{4}$/.test(s))s=s.slice(6)+'-'+s.slice(3,5)+'-'+s.slice(0,2);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw Error('Data inválida.');return s;}
function normalizeDraw(m,raw){const c=cfg(m),concurso=Number(raw.concurso??raw.numero);if(!Number.isSafeInteger(concurso)||concurso<1)throw Error('Número de concurso inválido.');const ex={trevos:raw.trevos??raw.trevosSorteados,mes:raw.mes,time:raw.time};if(m==='dia-de-sorte'&&ex.mes===undefined&&typeof raw.nomeTimeCoracaoMesSorte==='string'){const i=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'].indexOf(raw.nomeTimeCoracaoMesSorte.toLowerCase());if(i>=0)ex.mes=i+1;}
 const t=validateTicket(m,{dezenas:raw.dezenas??raw.listaDezenas,colunas:raw.colunas,...ex},{resultado:true}),date=raw.data??raw.dataApuracao;
 const r={...raw,...t,modalidade:m,concurso,data:date?isoDate(date):null,origem:String(raw.origem||'importado')};if(c.colunas)r.dezenas=t.colunas.map(a=>a[0]);const second=raw.dezenasSegundoSorteio??raw.listaDezenasSegundoSorteio;if(c.dupla&&second!==undefined)r.dezenasSegundoSorteio=validateTicket(m,{dezenas:second},{resultado:true}).dezenas;r.completo=(!c.extra||r[c.extra]!==undefined)&&(!c.dupla||!!r.dezenasSegundoSorteio);return r;
}
function history(m,records,op={}){
 const c=cfg(m),antes=op.antesDe??null;if(antes!==null&&(!Number.isSafeInteger(antes)||antes<1))throw Error('Corte de concurso inválido.');if(op.sorteio!==undefined&&(![1,2].includes(op.sorteio)||(op.sorteio===2&&!c.dupla)))throw Error('Extração inválida.');
 const map=new Map(),conflicts=new Set();let invalidos=0,duplicatas=0;
 for(const raw of records){const own=raw.modalidade,especial=c.especial&&['mega-sena','megasena'].includes(own)&&raw.especial==='mega-da-virada';if(own!==m&&own!==c.slug&&!especial)continue;if(c.especial&&own!==m&&raw.especial!=='mega-da-virada')continue;if(antes!==null&&Number(raw.concurso??raw.numero)>=antes)continue;
  try{let r=normalizeDraw(m,raw);if(op.sorteio===2){if(!r.dezenasSegundoSorteio)throw Error('Segundo sorteio ausente');r={...r,dezenas:r.dezenasSegundoSorteio};}const old=map.get(r.concurso);if(old){duplicatas++;if(JSON.stringify(tokens(m,old))!==JSON.stringify(tokens(m,r))||(old.data&&r.data&&old.data!==r.data)||[c.extra,'dezenasSegundoSorteio'].filter(Boolean).some(k=>old[k]!==undefined&&r[k]!==undefined&&JSON.stringify(old[k])!==JSON.stringify(r[k])))conflicts.add(r.concurso);else map.set(r.concurso,{...old,...r,data:r.data||old.data});}else map.set(r.concurso,r);}catch(e){invalidos++;}}
 const gaps=[];let bloco=0;const rows=[...map.values()].filter(r=>!conflicts.has(r.concurso)).sort((a,b)=>a.concurso-b.concurso).map((r,i,a)=>{if(i&&r.concurso!==a[i-1].concurso+1){bloco++;if(!c.especial)gaps.push([a[i-1].concurso+1,r.concurso-1]);}return {...r,bloco};});
 const meta={n:rows.length,primeiro:rows[0]?.concurso??null,ultimo:rows.at(-1)?.concurso??null,antesDe:antes,sorteio:op.sorteio||1,invalidos,duplicatas,conflitos:conflicts.size,lacunas:sum(gaps.map(([a,b])=>b-a+1)),intervalosAusentes:gaps,semComplemento:rows.filter(r=>!r.completo).length,semData:rows.filter(r=>!r.data).length,inicioAusente:rows.length&&!c.especial?rows[0].concurso-1:0,semRegistroAteCorte:antes!==null&&rows.length&&!c.especial?Math.max(0,antes-1-rows.at(-1).concurso):0,especial:!!c.especial};
 meta.assinatura=hash(JSON.stringify(rows.map(r=>[r.concurso,r.data,tokens(m,r),r[c.extra],r.dezenasSegundoSorteio,r.precoBase,r.faixasDetalhadas]))).toString(16);return {modalidade:m,rows,meta,masks:rows.map(r=>mask(tokens(m,r)))};
}
function distribution(m,t){const c=cfg(m),ps=Array(c.k+1).fill(0);if(c.colunas){ps[0]=1;for(const col of t.colunas){const p=col.length/10;for(let h=c.k;h>=0;h--)ps[h]=ps[h]*(1-p)+(h?ps[h-1]*p:0);}}else{const n=t.dezenas.length;for(let h=0;h<=c.k;h++)ps[h]=comb(n,h)*comb(c.N-n,c.k-h)/comb(c.N,c.k);}return ps;}
function wilson(k,n){if(!n)return null;const z=1.95996398454,p=k/n,d=1+z*z/n,a=(p+z*z/(2*n))/d,b=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return [Math.max(0,a-b),Math.min(1,a+b)];}
const percentile=(x,vs)=>vs.length?100*(vs.filter(v=>v<x-1e-12).length+.5*vs.filter(v=>Math.abs(v-x)<1e-12).length)/vs.length:null;
function quantile(xs,p){if(!xs.length)return null;const a=xs.slice().sort((a,b)=>a-b),pos=(a.length-1)*p,i=Math.floor(pos);return a[i]+(a[Math.min(i+1,a.length-1)]-a[i])*(pos-i);}
function intervals(indices,b){const rows=b.rows,values=[],occ=[];let ignored=0;indices.forEach((i,j)=>{const r=rows[i],prev=j?rows[indices[j-1]]:null,v=prev&&prev.bloco===r.bloco?r.concurso-prev.concurso:null;if(prev){if(v===null)ignored++;else values.push(v);}occ.push({concurso:r.concurso,data:r.data,intervalo:v});});const last=indices.length?rows[indices.at(-1)]:null;return {vezes:indices.length,ultimo:last?.concurso??null,atraso:last&&last.bloco===rows.at(-1).bloco&&!b.meta.semRegistroAteCorte?rows.at(-1).concurso-last.concurso:null,intervaloMedio:values.length?mean(values):null,menorIntervalo:values.length?Math.min(...values):null,maiorIntervalo:values.length?Math.max(...values):null,intervalosIgnorados:ignored,consecutivos:values.filter(v=>v===1).length,ocorrencias:occ,periodos:[0,1,2].map(p=>{const lo=Math.floor(rows.length*p/3),hi=Math.floor(rows.length*(p+1)/3);return {n:hi-lo,vezes:indices.filter(i=>i>=lo&&i<hi).length};})};}
function counts(m,t,b){const a=mask(tokens(m,t)),hs=b.masks.map(x=>intersection(a,x)),dist=Array(cfg(m).k+1).fill(0);hs.forEach(h=>dist[h]++);return {hs,dist};}
function structural(m,t){const c=cfg(m),ds=c.colunas?t.colunas.flat():t.dezenas,n=ds.length,a=ds.slice().sort((a,b)=>a-b),finais=Array(10).fill(0),faixas=Array(5).fill(0);for(const d of ds){finais[d%10]++;faixas[Math.min(4,Math.floor((d-c.base)/c.N*5))]++;}return {soma:sum(ds),media:mean(ds),amplitude:a.at(-1)-a[0],pares:ds.filter(d=>d%2===0).length,impares:ds.filter(d=>d%2!==0).length,consecutivos:a.slice(1).filter((x,i)=>x===a[i]+1).length,finais,faixas,dispersao:sd(ds),concentracao:Math.max(...faixas)/n};}
function frequency(m,t,b){const c=cfg(m);return tokens(m,t).map(d=>{const ids=[];b.masks.forEach((a,i)=>{if(a[d>>>5]&(1<<(d&31)))ids.push(i);});const v=intervals(ids,b),n=b.rows.length,nr=Math.min(30,n),p=c.colunas?.1:c.k/c.N;return {dezena:c.colunas?`${Math.floor(d/10)+1}:${d%10}`:d+c.base,...v,percentual:n?100*ids.length/n:null,frequenciaRecente:nr?ids.filter(i=>i>=n-nr).length/nr:null,frequenciaLonga:n?ids.length/n:null,janelaRecente:nr,atrasoMedio:v.intervaloMedio===null?null:v.intervaloMedio-1,maiorAtraso:v.maiorIntervalo===null?null:v.maiorIntervalo-1,esperado:p,desvio:n?ids.length/n-p:null,ic:wilson(ids.length,n)};});}
function analyze(m,input,records,op={}){
 const t=validateTicket(m,input),b=history(m,records,op),c=cfg(m),n=b.rows.length,{hs,dist}=counts(m,t,b),p=distribution(m,t),own=tokens(m,t);
 const faixas=dist.map((vezes,h)=>({acertos:h,percentual:n?100*vezes/n:null,ic:wilson(vezes,n),probabilidade:p[h],...intervals(hs.flatMap((v,i)=>v===h?[i]:[]),b)}));
 const minimos=dist.map((_,h)=>{const vezes=sum(dist.slice(h));return {acertos:h,vezes,percentual:n?100*vezes/n:null,probabilidade:sum(p.slice(h))};});
 const ranking=faixas.slice().sort((a,b)=>b.vezes-a.vezes||a.acertos-b.acertos),show=d=>c.colunas?`${Math.floor(d/10)+1}:${d%10}`:d+c.base;
 const detalhes=b.rows.map((r,i)=>{const tok=tokens(m,r);return {concurso:r.concurso,data:r.data,resultado:c.colunas?r.colunas:r.dezenas,acertos:hs[i],coincidentes:own.filter(d=>tok.includes(d)).map(show),naoCoincidentes:own.filter(d=>!tok.includes(d)).map(show),extras:c.extra?{campo:c.extra,jogo:t[c.extra]??null,resultado:r[c.extra]??null}:null};});
 const repetidas=b.rows.flatMap((r,i)=>{const same=c.colunas?t.colunas.every((a,j)=>a.length===1&&a[0]===r.colunas[j][0]):t.dezenas.length===c.k&&hs[i]===c.k;if(!same)return [];const e=c.extra;return [{concurso:r.concurso,data:r.data,completa:!e||t[e]!==undefined&&r[e]!==undefined&&JSON.stringify(t[e])===JSON.stringify(r[e])}];});
 const complete=new Set(repetidas.filter(x=>x.completa).map(x=>x.concurso));
 const complementos=c.extra?{campo:c.extra,completos:0,ausentes:0,conjuntas:[]}:null;
 if(complementos)for(let i=0;i<n;i++){const r=b.rows[i];if(t[c.extra]===undefined||r[c.extra]===undefined){complementos.ausentes++;continue;}const e=c.extra==='trevos'?t.trevos.filter(x=>r.trevos.includes(x)).length:Number(t[c.extra]===r[c.extra]);complementos.completos++;let f=complementos.conjuntas.find(x=>x.acertos===hs[i]&&x.extra===e);if(!f){f={acertos:hs[i],extra:e,vezes:0};complementos.conjuntas.push(f);}f.vezes++;}
 if(complementos)complementos.conjuntas.forEach(x=>x.percentual=100*x.vezes/complementos.completos);
 return {versao:VERSION,modalidade:m,jogo:t,base:b.meta,faixas,minimos,predominantes:ranking.slice(0,2).map(f=>f.acertos),raras:faixas.filter(f=>f.vezes&&f.percentual<1).map(f=>f.acertos),naoObservadas:faixas.filter(f=>!f.vezes).map(f=>f.acertos),estrutura:structural(m,t),dezenas:frequency(m,t,b),coberturaMedia:n?sum(hs)/(n*c.k):null,coberturaMediaDezenas:n?sum(hs)/(n*own.length):null,repetidas,repeticaoCompleta:intervals(b.rows.flatMap((r,i)=>complete.has(r.concurso)?[i]:[]),b),detalhes,complementos,conclusao:n?`Maior concentração histórica nas faixas de ${ranking[0].acertos} e ${ranking[1].acertos} acertos.`:'Sem concursos válidos neste recorte.',aviso};
}
const criterionNames=['soma','paridade','amplitude','consecutivos','dispersao','concentracao','finais','frequencia','atraso','paresTrios','repeticao','perfil'];
function vector(m,t,b,omit=-1){const c=cfg(m),s=structural(m,t),ts=tokens(m,t),n=ts.length,all=counts(m,t,b),hs=omit<0?all.hs:all.hs.filter((_,i)=>i!==omit),dist=all.dist.slice(),H=hs.length,p=distribution(m,t);if(omit>=0)dist[all.hs[omit]]--;
 if(!b.tokenLast){b.tokenLast=Array.from({length:128},()=>[-1,-1]);b.rows.forEach((r,i)=>tokens(m,r).forEach(d=>b.tokenLast[d]=[i,b.tokenLast[d][0]]));}const recent=b.rows.length-1===omit?b.rows.length-2:b.rows.length-1;
 const delays=ts.map(d=>{const i=b.tokenLast[d][0]===omit?b.tokenLast[d][1]:b.tokenLast[d][0];return i>=0&&recent>=0&&b.rows[i].bloco===b.rows[recent].bloco?b.rows[recent].concurso-b.rows[i].concurso:0;});
 return [s.media/c.N,s.pares/n,s.amplitude/c.N,s.consecutivos/Math.max(1,n-1),s.dispersao/c.N,s.concentracao,Math.max(...s.finais)/n,H?mean(hs)/n:0,mean(delays.map(x=>Math.min(5,x*(c.colunas?.1:c.k/c.N))))/5,H?mean(hs.map(h=>(comb(h,2)/Math.max(1,comb(n,2))+comb(h,3)/Math.max(1,comb(n,3)))/2)):0,H?hs.at(-1)/c.k:0,...dist.map((v,i)=>H?v/H-p[i]:0)];}
function center(xs){return {media:xs[0].map((_,j)=>mean(xs.map(x=>x[j]))),dp:xs[0].map((_,j)=>Math.max(.02,sd(xs.map(x=>x[j]))))};}
const distance=(v,model,w={})=>mean(v.map((x,j)=>Math.min(5,Math.abs(x-model.media[j])/model.dp[j])*(w[criterionNames[Math.min(j,11)]]??1)));
const referenceCache=new Map();
function reference(m,t,records,op={}){
 t=validateTicket(m,t);const b=history(m,records,op),n=op.amostras??2000;if(!Number.isInteger(n)||n<1000||n>10000)throw Error('Referência: 1.000–10.000 combinações.');if(b.rows.length<30)return {estado:'amostra insuficiente',n:b.rows.length,aviso};
 const seed=String(op.semente||'referencia-418'),v=vector(m,t,b),c=cfg(m),cacheKey=JSON.stringify([m,b.meta.assinatura,b.meta.antesDe,b.meta.sorteio,n,seed,t.dezenas?.length,t.colunas?.map(a=>a.length),t.trevos?.length]);let ref=referenceCache.get(cacheKey);
 if(!ref){const random=rng(seed+':referencia'),cal=Array.from({length:200},()=>vector(m,randomTicket(m,random,t),b)),same=c.colunas?t.colunas.every(a=>a.length===1):t.dezenas.length===c.k,historic=same?b.rows.map((r,i)=>({r,v:vector(m,r,b,i)})):[],model=center(historic.length?historic.map(x=>x.v):cal),scores=[],cover=[],samples=[];
  for(let i=0;i<n;i++){const ticket=randomTicket(m,random,t),vv=vector(m,ticket,b);scores.push(-distance(vv,model));cover.push(mean(counts(m,ticket,b).hs));if(i<80)samples.push({jogo:ticket,v:vv});}ref={historic,model,scores,cover,samples};if(referenceCache.size>=3)referenceCache.delete(referenceCache.keys().next().value);referenceCache.set(cacheKey,ref);}
 const {historic,model,scores,cover}=ref,score=-distance(v,model),percentil=percentile(score,scores);
 const periodos=[0,1,2].map(i=>{const rows=b.rows.slice(Math.floor(b.rows.length*i/3),Math.floor(b.rows.length*(i+1)/3)),bb={...b,rows,masks:rows.map(r=>mask(tokens(m,r))),tokenLast:null};return {primeiro:rows[0]?.concurso,ultimo:rows.at(-1)?.concurso,n:rows.length,distancia:distance(vector(m,t,bb),model),mediaAcertos:mean(counts(m,t,bb).hs)};});
 return {estado:'descritivo',semente:seed,amostras:n,calibracao:200,percentil,percentilHistorico:percentile(score,historic.map(x=>-distance(x.v,model))),percentilCobertura:percentile(mean(counts(m,t,b).hs),cover),classificacao:percentil>=25?'comportamento historicamente comum':'perfil menos semelhante à referência',score,periodos,historicosComparaveis:historic.length,similares:historic.map(x=>({concurso:x.r.concurso,data:x.r.data,distancia:distance(x.v,{media:v,dp:model.dp})})).sort((a,b)=>a.distancia-b.distancia).slice(0,20),aleatoriosSemelhantes:ref.samples.map(x=>({jogo:x.jogo,distancia:distance(x.v,{media:v,dp:model.dp})})).sort((a,b)=>a.distancia-b.distancia).slice(0,10),faixaAcaso:[quantile(cover,.025),quantile(cover,.975)],base:b.meta,aviso};
}
function unrank(xs,k,rank){const out=[];let start=0;for(let j=0;j<k;j++)for(let i=start;i<xs.length;i++){const rest=comb(xs.length-i-1,k-j-1);if(rank<rest){out.push(xs[i]);start=i+1;break;}rank-=rest;}return out;}
function groupPage(m,t,records,op={}){const b=history(m,records,op),xs=tokens(m,validateTicket(m,t)),size=Number(op.tamanho||2),offset=Number(op.inicio||0),limit=Number(op.limite||30);if(!Number.isInteger(size)||size<1||size>xs.length||!Number.isSafeInteger(offset)||offset<0||!Number.isInteger(limit)||limit<1||limit>200)throw Error('Página de subconjuntos inválida.');const total=comb(xs.length,size);if(!Number.isSafeInteger(total))throw Error('Total excede indexação exata.');const rows=[];for(let rank=offset;rank<Math.min(total,offset+limit);rank++){const g=unrank(xs,size,rank),gm=mask(g),ids=[];b.masks.forEach((a,i)=>{if(intersection(a,gm)===size)ids.push(i);});rows.push({indice:rank,grupo:g.map(d=>cfg(m).colunas?`${Math.floor(d/10)+1}:${d%10}`:d+cfg(m).base),...intervals(ids,b),percentual:b.rows.length?100*ids.length/b.rows.length:null});}return {total,tamanho:size,inicio:offset,limite:limit,linhas:rows,base:b.meta,exato:true};}
function portfolio(m,tickets){const ts=tickets.map(t=>validateTicket(m,t)),xs=ts.map(t=>tokens(m,t)),usage=new Map(),pairs=new Set(),triples=new Set(),overlaps=[],duplicates=[],seen=new Map();xs.forEach((a,i)=>{for(const d of a)usage.set(d,(usage.get(d)||0)+1);for(let j=0;j<a.length;j++)for(let k=j+1;k<a.length;k++){pairs.add(a[j]+':'+a[k]);for(let l=k+1;l<a.length;l++)triples.add(a[j]+':'+a[k]+':'+a[l]);}const kk=key(m,ts[i]);if(seen.has(kk))duplicates.push([seen.get(kk),i]);else seen.set(kk,i);for(let j=0;j<i;j++){const h=intersection(mask(a),mask(xs[j]));overlaps.push({a:j,b:i,iguais:h,distancia:1-h/new Set([...a,...xs[j]]).size});}});const ss=ts.map(t=>structural(m,t));return {jogos:ts.length,dezenas:usage.size,pares:pairs.size,trios:triples.size,sobreposicaoMedia:mean(overlaps.map(x=>x.iguais)),maiorSobreposicao:overlaps.length?Math.max(...overlaps.map(x=>x.iguais)):0,distanciaMedia:mean(overlaps.map(x=>x.distancia)),redundantes:duplicates,somas:ss.map(x=>x.soma),paridade:ss.map(x=>x.pares),perfisDistintos:new Set(ss.map(s=>[s.pares,Math.floor(s.media/5),s.consecutivos].join(':'))).size,sobreposicoes:overlaps,uso:[...usage].map(([d,vezes])=>({d,vezes})),nota:'União de grupos presentes nos jogos; não é chance de prêmio.'};}
function equivalents(m,t){const c=cfg(m);return c.colunas?t.colunas.reduce((v,a)=>v*a.length,1):comb(t.dezenas.length,c.min)*(c.extra==='trevos'?comb(t.trevos?.length||2,2):1);}
const currentCost=(m,t)=>cfg(m).preco*equivalents(m,validateTicket(m,t));
function financial(m,t,draw){const c=cfg(m),r=normalizeDraw(m,draw),h=hits(m,t,r),price=r.precoBase;if(!Number.isFinite(price)||price<=0)return {disponivel:false,motivo:'Preço histórico ausente.',acertos:h};if(c.extra&&(t[c.extra]===undefined||r[c.extra]===undefined)||c.dupla&&!r.dezenasSegundoSorteio)return {disponivel:false,motivo:'Complemento ou segundo sorteio ausente.',acertos:h};if(!Array.isArray(r.faixasDetalhadas))return {disponivel:false,motivo:'Rateio detalhado ausente.',acertos:h};let prize=0;
 const tiers=c.extra==='trevos'?[[6,[2]],[6,[0,1]],[5,[2]],[5,[0,1]],[4,[2]],[4,[0,1]],[3,[2]],[3,[1]],[2,[2]],[2,[1]]]:c.faixas.map(x=>[x,null]),draws=c.dupla?[r,{...r,dezenas:r.dezenasSegundoSorteio}]:[r];
 for(let di=0;di<draws.length;di++)for(const [tier,extra] of tiers){const hh=hits(m,t,draws[di]);let mult;if(c.colunas){let a=[1];for(let i=0;i<7;i++){const hit=t.colunas[i].includes(r.colunas[i][0])?1:0,next=Array(a.length+1).fill(0);a.forEach((v,j)=>{next[j]+=v*(t.colunas[i].length-hit);next[j+1]+=v*hit;});a=next;}mult=a[tier]||0;}else mult=c.min===c.k?comb(hh,tier)*comb(t.dezenas.length-hh,c.min-tier):Number(hh===tier);if(extra){const e=t.trevos.filter(x=>r.trevos.includes(x)).length;mult*=sum(extra.map(h=>comb(e,h)*comb(t.trevos.length-e,2-h)));}if(!mult)continue;const f=r.faixasDetalhadas.find(f=>f.acertos===tier&&(extra===null||JSON.stringify(f.extras??[f.extra])===JSON.stringify(extra))&&(f.sorteio??1)===di+1);if(!f||!Number.isFinite(f.premio)||f.premio<0)return {disponivel:false,motivo:'Faixa de prêmio ausente.',acertos:h};prize+=mult*f.premio;}
 if(['mes','time'].includes(c.extra)&&t[c.extra]===r[c.extra]){const f=r.faixasDetalhadas.find(f=>f.complemento===c.extra);if(!f||!Number.isFinite(f.premio)||f.premio<0)return {disponivel:false,motivo:'Prêmio complementar ausente.'};if(c.extra==='mes'&&t.dezenas.length>c.min&&!Number.isInteger(f.multiplicidade))return {disponivel:false,motivo:'Multiplicidade do mês não documentada.'};prize+=(f.multiplicidade??1)*f.premio;}
 const custo=price*equivalents(m,t);return {disponivel:true,acertos:h,custo,premio:prize,liquido:prize-custo};}
function financialMetrics(rows){const valid=rows.filter(x=>x.disponivel);if(valid.length!==rows.length||!rows.length)return {disponivel:false,cobertura:rows.length?valid.length/rows.length:0,motivo:'ROI indisponível: preço, rateio e complementos completos são obrigatórios em todo o recorte.'};let acc=0,peak=0,dd=0,dry=0,maxDry=0;const curve=[];for(const r of rows){acc+=r.liquido;peak=Math.max(peak,acc);dd=Math.max(dd,peak-acc);dry=r.premio===0?dry+1:0;maxDry=Math.max(maxDry,dry);curve.push(acc);}const custo=sum(rows.map(r=>r.custo)),premio=sum(rows.map(r=>r.premio));return {disponivel:true,cobertura:1,custo,premio,liquido:premio-custo,roi:(premio-custo)/custo,drawdown:dd,sequenciaSemPremio:maxDry,curva:curve};}
function monteCarlo(m,t,op={}){t=validateTicket(m,t);const n=op.amostras??10000;if(!Number.isInteger(n)||n<1000||n>100000)throw Error('Use 1.000–100.000 simulações.');const seed=String(op.semente||'simulacao-418'),random=rng(seed),c=cfg(m),dist=Array(c.k+1).fill(0),target=tokens(m,t),gm=mask(target),groups=Array.from({length:Math.min(5,c.k,target.length)},(_,i)=>({tamanho:i+1,tokens:target.slice(0,i+1),vezes:0,atraso:0,maiorAusencia:0}));let last=-1,maxAbs=0,repeated=0;
 for(let i=0;i<n;i++){const d=c.colunas?{colunas:Array.from({length:7},()=>[Math.floor(random()*10)])}:{dezenas:sample(Array.from({length:c.N},(_,i)=>i+c.base),c.k,random)},dm=mask(tokens(m,d)),h=intersection(gm,dm);dist[h]++;if(h===c.k){repeated++;if(last>=0)maxAbs=Math.max(maxAbs,i-last-1);last=i;}for(const g of groups)if(intersection(mask(g.tokens),dm)===g.tamanho){g.vezes++;g.atraso=0;}else{g.atraso++;g.maiorAusencia=Math.max(g.maiorAusencia,g.atraso);}}
 return {versao:VERSION,modalidade:m,jogo:t,semente:seed,n,simulado:true,faixas:dist.map((vezes,h)=>({acertos:h,vezes,percentual:100*vezes/n,ic:wilson(vezes,n),probabilidade:distribution(m,t)[h]})),coberturaCompleta:{vezes:repeated,maiorIntervaloSemCobertura:repeated>1?maxAbs:null,ausenciaAtual:last>=0?n-last-1:null},grupos:groups.map(g=>({...g,grupo:g.tokens.map(d=>c.colunas?`${Math.floor(d/10)+1}:${d%10}`:d+c.base)})),nota:'Sorteios uniformes simulados, nunca gravados como resultados reais. Cada grupo listado é específico; não representa todos os grupos desse tamanho.'};}
root.LL18={VERSION,aviso,rules,cfg,sum,mean,sd,comb,hash,rng,sample,nums,parseTicket,validateTicket,tokens,key,mask,intersection,hits,randomTicket,normalizeDraw,history,distribution,wilson,percentile,quantile,intervals,counts,structural,frequency,analyze,criterionNames,vector,center,distance,reference,unrank,groupPage,portfolio,equivalents,currentCost,financial,financialMetrics,monteCarlo};
if(typeof module!=='undefined'&&module.exports)module.exports=root.LL18;
})(globalThis);
